import Link from 'next/link';
import { Activity, ArrowRight, BrainCircuit, Layers3, ShieldAlert, Workflow } from 'lucide-react';
import { pageMetadata } from '@/lib/seo';
export const metadata = pageMetadata({ title: 'Predictive Maintenance Solutions by Machine Risk', description: 'Match monitoring depth to machine risk: start with critical motors, pumps, fans and gearboxes, extend sensor coverage and prioritise maintenance with AI.', path: '/solutions' });

const tiers = [
  { icon: BrainCircuit, level: '01 · AI SHIELDS', title: 'Equipment-specific AI', description: 'Apply equipment-specific analysis to critical assets where an unexpected stop carries the greatest operational risk.', includes: ['Kilns, mills, cranes, furnaces, fillers and run-out tables', 'Dynamic FMEA to structure fault analysis', '24×7 human expert review'] },
  { icon: Activity, level: '02 · FLEX RELIABILITY', title: 'Flexible plant coverage', description: 'Extend condition monitoring across the rest of the plant using the sensing approach that fits each asset.', includes: ['Wired piezoelectric or MEMS sensors', 'Wireless self-powered monitoring tags', 'Ingest existing third-party sensor data; no rip-and-replace'] },
  { icon: ShieldAlert, level: '03 · PLANT FUSION', title: 'Risk-based plant ranking', description: 'Rank what to maintain, stock and replace by risk, and share the resulting context with enterprise systems.', includes: ['Risk-based ranking using RBI, RCM and FMEA', 'Prioritised maintenance, spares and replacement planning', 'Open API and MCP feed for enterprise systems'] },
];

const equipmentBorne = ['Bearing wear', 'Unbalance', 'Misalignment', 'Looseness', 'Cavitation', 'Resonance', 'Lubrication degradation', 'Gear-mesh anomalies'];
const processInduced = ['Kiln ring formation', 'Thermal overstress', 'Cyclone coating build-up', 'Ladle heat drift', 'Hot-strip thermal fatigue', 'Web tension drift'];

export default function SolutionsPage() {
  return <main id="main">
    <section className="page-hero solutions-page-hero"><div className="container"><Link className="breadcrumb" href="/">RevUptime <span>/</span> Solutions</Link><span className="section-eyebrow">A LAYERED APPROACH TO RELIABILITY</span><h1>Match monitoring depth to machine risk.</h1><p>Start with critical assets, extend sensor coverage to fit the plant, and help teams rank the work that needs attention.</p></div></section>
    <section className="section"><div className="container"><div className="section-heading"><span className="section-eyebrow">SOLUTION TIERS</span><h2>Three layers. One maintenance workflow.</h2><p>Each layer adds context to how a plant monitors, investigates and prioritises equipment.</p></div><div className="three-grid solution-tier-grid">{tiers.map(({icon:Icon,level,title,description,includes})=><article className="solution-tier-card" key={title}><span className="solution-tier-icon"><Icon size={24}/></span><span className="micro">{level}</span><h3>{title}</h3><p>{description}</p><ul>{includes.map((item)=><li key={item}>{item}</li>)}</ul></article>)}</div></div></section>
    <section className="section light-section"><div className="container"><div className="section-heading"><span className="section-eyebrow">FAILURE MODE COVERAGE</span><h2>Equipment-borne and process-induced modes.</h2><p>RevUptime’s failure-mode framework covers 20+ modes in each family. These selected examples show why condition signals need to be interpreted with machine and process context.</p></div><div className="failure-explainer"><article><div><Activity size={20}/><span>20+ EQUIPMENT-BORNE MODES</span></div><h3>Faults in the asset or its components</h3><p>Mechanical condition changes associated with bearings, rotating forces, fits, lubrication and drive components.</p><ul>{equipmentBorne.map((fault)=><li key={fault}>{fault}</li>)}</ul></article><span className="failure-explainer-connector"><Workflow size={24}/><small>Signals + context</small></span><article><div><Layers3 size={20}/><span>20+ PROCESS-INDUCED MODES</span></div><h3>Process conditions affect performance</h3><p>Changes driven by thermal, material, flow or production behaviour across specific industrial processes.</p><ul>{processInduced.map((fault)=><li key={fault}>{fault}</li>)}</ul></article></div><p className="failure-caveat">Examples are not a complete mode list or an automatic diagnosis. Detectability depends on installed sensors, signal quality, operating context and site validation. Confirm suspected causes with qualified personnel and site procedures.</p></div></section>
    <section className="section"><div className="container solution-cta"><div><span className="section-eyebrow">START WITH YOUR CRITICAL ASSETS</span><h2>Build a monitoring plan for your plant.</h2><p>Review asset suitability, operating context and pilot priorities with the RevUptime team.</p></div><Link href="/contact" className="button">Discuss your plant <ArrowRight size={16}/></Link></div></section>
  </main>;
}
