import Image from 'next/image';
import type { Metadata } from 'next';
import { JsonLd } from '@/components/seo/json-ld';
import { pageMetadata, breadcrumbJsonLd, faqJsonLd, serviceJsonLd, SITE_URL, ORG_ID } from '@/lib/seo';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Check, MapPin, ShieldCheck, PhoneCall, Cog, LockKeyhole } from 'lucide-react';
import { SectionHeading, HowItWorks, ProductSection, CopilotSection, MobileSection, AssetSection, WhySection, PilotSection, OutcomesSection, CompanySection, FinalCTA } from '@/components/marketing/sections';
import { HeroDashboard } from '@/components/product/hero-dashboard';
import { LeadForm } from '@/components/marketing/lead-form';
import { industryPages, pilotFaq as faq } from '@/data/pages';
import { assets } from '@/data/content';
import { FAQSection } from '@/components/marketing/faq-section';

const routes=['product','solutions/predictive-maintenance','industries/steel','industries/mining','industries/manufacturing','industries/cement','industries/chemicals-fertilizer','industries/pulp-paper','industries/tires','industries/food-beverage','industries/pharma','industries/sponge-iron','industries/power','industries/ports','pilot','about','contact','privacy','terms','sign-in'];
export function generateStaticParams(){return routes.map(route=>({slug:route.split('/')}));}
const pageMeta:Record<string,{title:string;description:string;crumb:string}>={
 product:{title:'AI Condition Monitoring & Reliability Platform',crumb:'Product',description:'Continuous vibration and temperature monitoring, machine-specific baselines, an AI Reliability Copilot and mobile alerts for industrial maintenance teams.'},
 'solutions/predictive-maintenance':{title:'Predictive Maintenance Solutions for Indian Industry',crumb:'Predictive Maintenance',description:'Predictive maintenance for motors, pumps, gearboxes, fans, conveyors and crushers: continuous condition trends, baselines and prioritised alerts for Indian plants.'},
 pilot:{title:'90-Day Predictive Maintenance Pilot (5 Machines)',crumb:'Pilot Program',description:'Evaluate RevUptime on five critical machines for 90 days: sensors installed, baselines established and findings reviewed with your maintenance team.'},
 about:{title:'About Us — Revapex AI, Bhubaneswar, Odisha',crumb:'About',description:'RevUptime is a product of Revapex AI Private Limited, Bhubaneswar, building practical AI condition monitoring for the steel, mining and process plants of Odisha and India.'},
 contact:{title:'Contact Us — Book a Predictive Maintenance Pilot',crumb:'Contact',description:'Talk to RevUptime about a 90-day predictive maintenance pilot for your plant. Based in Bhubaneswar, serving Odisha and Eastern India.'},
 privacy:{title:'Privacy Policy',crumb:'Privacy Policy',description:'How Revapex AI Private Limited handles information submitted through the RevUptime website enquiry forms.'},
 terms:{title:'Website Terms',crumb:'Website Terms',description:'Terms of use for the RevUptime website, including illustrative product previews and pilot enquiries.'},
 'sign-in':{title:'Customer Access',crumb:'Customer Access',description:'Customer workspace access for RevUptime pilot and deployment customers.'},
};
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const path=slug.join('/');const industry=slug[0]==='industries'?industryPages[slug[1] as keyof typeof industryPages]:null;if(industry)return pageMetadata({title:`Predictive Maintenance for ${industry.title}`,description:industry.description,path:`/${path}`});const m=pageMeta[path];if(!m)return {title:'Page not found',robots:{index:false}};return pageMetadata({title:m.title,description:m.description,path:`/${path}`,noindex:path==='sign-in'});}
function structuredData(path:string,slug:string[]):object[]{
 const industry=slug[0]==='industries'?industryPages[slug[1] as keyof typeof industryPages]:null;
 if(industry)return [breadcrumbJsonLd([{name:'Industries',path:'/industries'},{name:industry.title,path:`/${path}`}]),serviceJsonLd({name:`Predictive maintenance for ${industry.title}`,description:industry.description,path:`/${path}`,serviceType:'Predictive maintenance and condition monitoring'})];
 const m=pageMeta[path];if(!m)return [];
 const crumbs=path==='solutions/predictive-maintenance'?[{name:'Solutions',path:'/solutions'},{name:m.crumb,path:`/${path}`}]:[{name:m.crumb,path:`/${path}`}];
 const data:object[]=[breadcrumbJsonLd(crumbs)];
 if(path==='product')data.push({'@context':'https://schema.org','@type':'SoftwareApplication',name:'RevUptime',applicationCategory:'BusinessApplication',applicationSubCategory:'Predictive maintenance and condition monitoring',operatingSystem:'Web, Android, iOS',url:`${SITE_URL}/product`,description:m.description,featureList:['Vibration and temperature condition monitoring','Machine-specific baselines','Prioritised alerts','AI Reliability Copilot','Explainable AI evidence','Mobile access','Maintenance history'],publisher:{'@id':ORG_ID}});
 if(path==='solutions/predictive-maintenance')data.push(serviceJsonLd({name:m.title,description:m.description,path:`/${path}`,serviceType:'Predictive maintenance'}));
 if(path==='pilot')data.push(faqJsonLd(faq),serviceJsonLd({name:'90-day predictive maintenance pilot',description:m.description,path:'/pilot',serviceType:'Predictive maintenance pilot'}));
 return data;
}
function PageHero({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:React.ReactNode}){return <section className="page-hero"><div className="container"><Link className="breadcrumb" href="/">RevUptime <span>/</span> {eyebrow}</Link><span className="section-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p>{children||<div className="hero-buttons"><Link className="button" href="/contact">Book a 90-Day Pilot</Link><Link className="button secondary" href="/product">Explore the platform</Link></div>}</div></section>;}
function IndustryPage({name}:{name:keyof typeof industryPages}){const d=industryPages[name];return <><PageHero eyebrow={d.eyebrow} title={d.headline} description={d.description}/><section className="section"><div className="container two-column"><SectionHeading eyebrow={d.title.toUpperCase()} title={d.challenge} description={d.copy}/><div className="covered-assets"><h3>Where RevUptime helps</h3>{d.assets.map(x=><div key={x}><Cog size={19}/>{x}</div>)}</div></div></section><HowItWorks/><section className="section"><div className="container narrow"><SectionHeading eyebrow="A FOCUSED FIRST STEP" title="Start with the assets that matter most." description={d.pilot}/><p className="section-body">Each pilot begins with a suitability review. Mounting, environment, operating range and connectivity are assessed before an asset is included.</p></div></section><PilotSection/><FinalCTA/></>;}
export default async function ContentPage({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const path=slug.join('/');if(!routes.includes(path))notFound();let content:React.ReactNode;
 if(slug[0]==='industries'){content=<IndustryPage name={slug[1] as keyof typeof industryPages}/>;}
 else if(path==='product'){content=<><section className="page-hero platform-hero"><div className="container hero-grid"><div><span className="section-eyebrow">THE REVUPTIME PLATFORM</span><h1>AI condition monitoring.<br/>A clearer picture.</h1><p>From continuous condition monitoring to AI-assisted investigation, give your team the context to maintain with confidence.</p><div className="hero-buttons"><Link className="button" href="/contact">Book a 90-Day Pilot</Link><a className="text-link" href="#dashboard">Explore the product</a></div></div><HeroDashboard/></div></section><ProductSection/><HowItWorks/><CopilotSection/><MobileSection/><FAQSection product/><FinalCTA/></>;}
 else if(path==='solutions/predictive-maintenance'){content=<><PageHero eyebrow="PREDICTIVE MAINTENANCE" title="Predictive maintenance before the next inspection." description="Move beyond periodic checks with continuous vibration and temperature trends, machine baselines and prioritised alerts."/><OutcomesSection/><section className="section light-section"><div className="container"><SectionHeading eyebrow="MONITOR WHAT MATTERS" title="Every asset has its own operating story." description="Establish context at the machine level. Compare changes with normal behaviour and let qualified engineers investigate the cause."/><div className="asset-grid asset-photo-grid">{assets.map((a,i)=><article id={a.icon} key={a.name} className="solution-asset solution-photo-card"><div className="asset-photo"><Image src={`/images/equipment/${a.icon}.webp`} alt={a.imageAlt} fill sizes="(max-width: 600px) 100vw, (max-width: 900px) 50vw, 33vw"/><span className="asset-photo-label">ASSET / 0{i+1}</span></div><div className="asset-photo-copy"><h3>{a.name}</h3><p>{a.detail}</p><p>Track condition over time, review alerts and record inspections against the asset’s history.</p></div></article>)}</div><p className="industry-image-note">Illustrative equipment imagery.</p></div></section><HowItWorks/><CopilotSection/><FinalCTA/></>;}
 else if(path==='pilot'){content=<><PageHero eyebrow="THE 90-DAY PILOT" title="A 90-day predictive maintenance pilot." description="Evaluate condition monitoring on your own plant floor, with a focused pilot built around the equipment and questions that matter to your team."/><PilotSection/><section className="section"><div className="container"><SectionHeading eyebrow="A CLEAR PATH FROM DAY ONE" title="A practical pilot, with a shared plan."/><div className="four-grid pilot-timeline">{[['01','Scope together','Choose suitable critical assets and agree what a useful evaluation looks like.'],['02','Install & baseline','Review mounting and connectivity, then establish machine-specific operating patterns.'],['03','Monitor & investigate','Review trends and alerts alongside maintenance observations and operating context.'],['04','Review & decide','Discuss the findings, team experience and suitability for a wider rollout.']].map(([n,title,text])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section light-section"><div className="container faq-layout"><SectionHeading eyebrow="BEFORE YOU START" title="Your pilot questions, answered."/><div className="faq-list">{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section><FinalCTA/></>;}
 else if(path==='about'){content=<><PageHero eyebrow="ABOUT REVUPTIME" title="AI predictive maintenance, built in Odisha for India." description="We’re building practical condition monitoring for the plants powering India’s industrial growth."/><div className="about-story"><CompanySection/></div><section className="section light-section"><div className="container two-column"><SectionHeading eyebrow="OUR FIRST FOCUS" title="Make modern machine monitoring practical." description="RevUptime is a product of Revapex AI Private Limited, based in Bhubaneswar, Odisha."/><div className="editorial-copy"><p>We are starting close to the steel, mining, metals and process industries of Odisha and Eastern India. These operations need clearer machine visibility without a complex enterprise reliability program on day one.</p><p>Our approach connects sensors, machine history and AI-assisted troubleshooting in a workflow built around maintenance teams.</p><p>We start with a focused pilot, evaluate real conditions and let the results guide what comes next.</p></div></div></section><WhySection/><FinalCTA/></>;}
 else if(path==='contact'){content=<section className="contact-page"><div className="container contact-grid"><div className="contact-copy"><span className="section-eyebrow">LET’S KEEP YOUR MACHINES RUNNING</span><h1>Book a predictive<br/>maintenance pilot.</h1><p>Tell us about your equipment. We’ll discuss how a focused 90-day pilot could work in your operation.</p><div className="contact-points">{['Start with five critical machines','Establish machine-specific baselines','Review the value with your team'].map(x=><div key={x}><Check size={18}/>{x}</div>)}</div><div className="contact-next"><PhoneCall size={22}/><h3>What happens next?</h3><p>A RevUptime team member will discuss asset suitability, your maintenance priorities and the pilot scope.</p></div><div className="contact-location"><MapPin size={18}/><span>Bhubaneswar, Odisha, India<br/><small>Initially serving Odisha and Eastern India.</small></span></div></div><LeadForm/></div></section>;}
 else if(path==='sign-in'){content=<section className="section access-page"><div className="container narrow"><span className="access-icon"><LockKeyhole size={28}/></span><span className="section-eyebrow">CUSTOMER ACCESS</span><h1>Your plant workspace.</h1><p>Customer workspaces are provisioned during pilot onboarding. Use the secure workspace link provided by your RevUptime contact.</p><div className="access-note"><ShieldCheck size={20}/><p>This marketing website does not collect customer passwords or connect to live plant data.</p></div><Link href="/contact" className="button">Request workspace assistance</Link><Link href="/product" className="text-link">Explore the product preview</Link></div></section>;}
 else {const privacy=path==='privacy';content=<section className="section legal-page"><div className="container narrow"><span className="section-eyebrow">REVUPTIME</span><h1>{privacy?'Privacy Policy':'Website Terms'}</h1><p className="legal-date">Last updated: 29 September 2026</p>{privacy?<><h2>Information you choose to share</h2><p>The pilot enquiry form asks for your name, business contact details, company, plant location, role and monitoring requirements. Please do not include sensitive plant data or confidential equipment documents in the message field.</p><h2>How your enquiry is used</h2><p>Information submitted successfully is used by Revapex AI Private Limited to respond to your enquiry, discuss asset suitability and coordinate a potential pilot. Submission does not automatically subscribe you to a marketing newsletter.</p><h2>Form delivery and storage</h2><p>A successful confirmation appears only after the configured enquiry service accepts your request. If delivery is unavailable, the form explains that your details have not been sent. Downloading a copy saves the enquiry on your own device.</p><h2>Website operation</h2><p>This version of the website does not use advertising trackers or analytics cookies. The hosting service may process technical request information to deliver and protect the website. Interactive product previews contain illustrative data.</p><h2>Your requests</h2><p>For questions about information you have submitted, use the <Link href="/contact">contact form</Link> or your existing RevUptime contact. You can ask for access, correction or removal of your enquiry information.</p></>:<><h2>About this website</h2><p>RevUptime is a product of Revapex AI Private Limited, Bhubaneswar, Odisha, India. This website introduces our AI-assisted condition-monitoring and predictive-maintenance offering.</p><h2>Illustrative product previews</h2><p>Dashboard readings, alerts, maintenance records, health scores and Copilot responses shown here are demonstrations. They are not live plant data or evidence of a customer deployment.</p><h2>Engineering decisions</h2><p>AI guidance supports trained maintenance personnel and does not replace engineering judgment. Follow equipment documentation and plant safety procedures before inspecting or working on machinery.</p><h2>Pilots and commercial scope</h2><p>Submitting an enquiry does not create a purchase or service agreement. Asset suitability, scope, price, implementation responsibilities and data-handling arrangements are agreed separately before a pilot starts.</p><h2>Availability</h2><p>Features and availability are subject to the agreed pilot scope. This website does not promise detection of every fault, guaranteed downtime reductions or a specific financial outcome.</p></>}</div></section>;}
 const jsonLd=structuredData(path,slug);
 return <main id="main">{content}{jsonLd.length>0&&<JsonLd data={jsonLd}/>}</main>;
}
