'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Activity, Radio, Sparkles, Thermometer, MoreHorizontal, ArrowUpRight } from 'lucide-react';
import { TrendChart } from './trend-chart';
export function HeroDashboard() {
 const [range,setRange] = useState('24h');
 return <div className="hero-visual"><div className="signal-label"><Radio size={14}/> MACHINE SIGNAL. CLEAR DIRECTION.</div><div className="hero-dash"><div className="dash-top"><span><Activity size={18}/> Asset intelligence</span><span className="sample-tag">Product preview</span></div><div className="dash-body"><div className="asset-title"><div><span className="micro">ROTATING EQUIPMENT / M-104</span><h3>ID Fan Motor <span>M-104</span></h3></div><MoreHorizontal size={20} aria-hidden="true"/></div><div className="asset-summary"><div className="health-ring"><div><strong>72</strong><span>/ 100</span></div></div><div><span className="status watch">Watch</span><p>Machine health score</p></div><div className="sensor-connected"><span className="dot"/> Sensor connected</div></div><div className="metric-row"><div><span><Activity size={14}/> Vibration</span><strong>4.2 <small>mm/s</small></strong><p>30-day baseline: 2.1 mm/s</p></div><div><span><Thermometer size={14}/> Temperature</span><strong>68<small>°C</small></strong><p><span className="trend-up">+32%</span> vibration, last 24h</p></div></div><div className="chart-heading"><span>Vibration trend <small>mm/s</small></span><div className="segmented">{['24h','7d','30d'].map(r=><button key={r} aria-pressed={range===r} onClick={()=>setRange(r)} className={range===r?'selected':''}>{r}</button>)}</div></div><TrendChart range={range} id="hero-chart"/><div className="chart-key"><span><i/> Vibration</span><span><i/> Normal baseline</span></div><div className="ai-insight"><div className="insight-icon"><Sparkles size={17}/></div><div><span className="micro">RELIABILITY COPILOT</span><h4>Abnormal vibration trend detected</h4><p>Vibration has remained above its normal operating baseline for 3.4 hours. Inspect drive-end bearing condition and mounting before the next production cycle.</p><Link href="/product#copilot">View analysis <ArrowUpRight size={14}/></Link></div></div></div></div><div className="visual-caption"><span className="live-line"/> Continuous visibility. Informed maintenance.<span>Illustrative product data</span></div></div>;
}
